In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
title_file = "Resources/ImdbTitleBasics.csv"
title_df = pd.read_csv(title_file)
title_df.tail()

/Users/rachelthorpe/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
1048570,tt10140376,tvSeries,Começar do Zero,Começar do Zero,0,2019,\N,90,Reality-TV
1048571,tt10140378,tvEpisode,Corey Hart,Corey Hart,0,2019,\N,\N,Talk-Show
1048572,tt1014037,tvEpisode,Escape,Escape,0,2008,\N,29,Documentary
1048573,tt10140380,short,Fear of Dogs,Fear of Dogs,0,1994,\N,\N,"Drama,Short"
1048574,tt10140382,tvEpisode,Wondercon Anaheim 2019 (Highlights),Wondercon Anaheim 2019 (Highlights),0,2019,\N,\N,Music

In [4]:
ratings_file = "Resources/ImdbTitleRatings.csv"
ratings_df = pd.read_csv(ratings_file)
ratings_df.tail()

            tconst  averageRating  numVotes
1048570  tt7512616            9.0         5
1048571  tt7512624            5.5       931
1048572  tt7512632            3.4        33
1048573  tt7512636            6.4        22
1048574  tt7512670            7.0        49

In [5]:
title_df

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
1048570,tt10140376,tvSeries,Começar do Zero,Começar do Zero,0,2019,\N,90,Reality-TV
1048571,tt10140378,tvEpisode,Corey Hart,Corey Hart,0,2019,\N,\N,Talk-Show
1048572,tt1014037,tvEpisode,Escape,Escape,0,2008,\N,29,Documentary
1048573,tt10140380,short,Fear of Dogs,Fear of Dogs,0,1994,\N,\N,"Drama,Short"
1048574,tt10140382,tvEpisode,Wondercon Anaheim 2019 (Highlights),Wondercon Anaheim 2019 (Highlights),0,2019,\N,\N,Music

In [6]:
title_df['tconst'] = title_df['tconst'].str[2:]
title_df

In [7]:
title_df['tconst'] = title_df['tconst'].astype(int)
title_df

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,1,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,2,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,3,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,4,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,5,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
1048570,10140376,tvSeries,Começar do Zero,Começar do Zero,0,2019,\N,90,Reality-TV
1048571,10140378,tvEpisode,Corey Hart,Corey Hart,0,2019,\N,\N,Talk-Show
1048572,1014037,tvEpisode,Escape,Escape,0,2008,\N,29,Documentary
1048573,10140380,short,Fear of Dogs,Fear of Dogs,0,1994,\N,\N,"Drama,Short"
1048574,10140382,tvEpisode,Wondercon Anaheim 2019 (Highlights),Wondercon Anaheim 2019 (Highlights),0,2019,\N,\N,Music

In [8]:
ratings_df['tconst']=ratings_df['tconst'].str[2:].astype(int)
ratings_df

          tconst  averageRating  numVotes
0              1            5.6      1694
1              2            6.0       210
2              3            6.5      1441
3              4            6.1       122
4              5            6.1      2240
...          ...            ...       ...
1048570  7512616            9.0         5
1048571  7512624            5.5       931
1048572  7512632            3.4        33
1048573  7512636            6.4        22
1048574  7512670            7.0        49

[1048575 rows x 3 columns]

In [10]:
title_df_renamed = title_df.rename(columns={"tconst":"id"})
title_df_renamed

,id,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,1,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,2,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,3,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,4,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,5,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
1048570,10140376,tvSeries,Começar do Zero,Começar do Zero,0,2019,\N,90,Reality-TV
1048571,10140378,tvEpisode,Corey Hart,Corey Hart,0,2019,\N,\N,Talk-Show
1048572,1014037,tvEpisode,Escape,Escape,0,2008,\N,29,Documentary
1048573,10140380,short,Fear of Dogs,Fear of Dogs,0,1994,\N,\N,"Drama,Short"
1048574,10140382,tvEpisode,Wondercon Anaheim 2019 (Highlights),Wondercon Anaheim 2019 (Highlights),0,2019,\N,\N,Music

In [11]:
ratings_df_renamed = ratings_df.rename(columns={"tconst":"id"})
ratings_df_renamed

              id  averageRating  numVotes
0              1            5.6      1694
1              2            6.0       210
2              3            6.5      1441
3              4            6.1       122
4              5            6.1      2240
...          ...            ...       ...
1048570  7512616            9.0         5
1048571  7512624            5.5       931
1048572  7512632            3.4        33
1048573  7512636            6.4        22
1048574  7512670            7.0        49

[1048575 rows x 3 columns]

In [12]:
title_df_clean = title_df_renamed.drop(columns=["endYear", "isAdult"])
title_df_clean

,id,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres
0,1,short,Carmencita,Carmencita,1894,1,"Documentary,Short"
1,2,short,Le clown et ses chiens,Le clown et ses chiens,1892,5,"Animation,Short"
2,3,short,Pauvre Pierrot,Pauvre Pierrot,1892,4,"Animation,Comedy,Romance"
3,4,short,Un bon bock,Un bon bock,1892,12,"Animation,Short"
4,5,short,Blacksmith Scene,Blacksmith Scene,1893,1,"Comedy,Short"
...,...,...,...,...,...,...,...
1048570,10140376,tvSeries,Começar do Zero,Começar do Zero,2019,90,Reality-TV
1048571,10140378,tvEpisode,Corey Hart,Corey Hart,2019,\N,Talk-Show
1048572,1014037,tvEpisode,Escape,Escape,2008,29,Documentary
1048573,10140380,short,Fear of Dogs,Fear of Dogs,1994,\N,"Drama,Short"
1048574,10140382,tvEpisode,Wondercon Anaheim 2019 (Highlights),Wondercon Anaheim 2019 (Highlights),2019,\N,Music

In [14]:
title_df_clean = title_df_clean['titleType','primaryTitle', 'originalTitle', 'startYear', 'runtimeMinutes'].str.lower()
title_df_clean

KeyError: ('titleType', 'primaryTitle', 'originalTitle', 'startYear', 'runtimeMinutes')